# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# This file is based on Astropy's CI-helpers:
# https://github.com/astropy/ci-helpers

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "4.6.14" # Temporary fix while https://github.com/conda/conda/issues/8865 persists
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      TEST_CMD: "python -m unittest discover --verbose"
      CONDA_CHANNELS: "default conda-forge"
      CONDA_DEPENDENCIES: "numpy scipy cython scikit-image crystals pywavelets npstreams pyyaml"
      PIP_DEPENDENCIES: ""

  matrix:

      - PYTHON_VERSION: "3.6"
      - PYTHON_VERSION: "3.7"
      - PYTHON_VERSION: "3.8"
      - PYTHON_VERSION: "3.9"

matrix:
   fast_finish: true

platform:
    -x64

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - docs/*
    - external/*
    - '**/*.rst'

install:

    # Install Miniconda
    - "git clone . ci-helpers"
    - "powershell .appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Test that PATH is set correctly
    - "conda --version"
    - "python --version"

# Not a .NET project, we build ci-helpers in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% %TEST_CMD%"

on_success:
